title: Ertis Seferi
description: "MS Computer Science — Robotics, Computer Vision & Machine Learning"
baseurl: ""
url: "https://ertisseferi.github.io"

collections:
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
